{% set name = "googlemaps" %}
{% set version = "4.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/googlemaps-{{ version }}.tar.gz
  sha256: 3055fcbb1aa262a9159b589b5e6af762b10e80634ae11c59495bd44867e47d88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - requests >=2.20.0,<3.0
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.20.0,<3.0

test:
  imports:
    - googlemaps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googlemaps/google-maps-services-python
  summary: Python client library for Google Maps Platform
  license: Apache-2.0
  license_file: LICENSE  
  description: |
    Use Python? Want to geocode something? Looking for directions? Maybe matrices of directions? This library brings the Google Maps API Web Services to your Python application. Analytics
  doc_url: https://github.com/googlemaps/google-maps-services-python
  dev_url: https://github.com/googlemaps/google-maps-services-python

extra:
  recipe-maintainers:
    - david-gang
    - giswqs
